### ISSUE TITLE
Point to "Containerizing microservices" guide

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-sessions#42]
Point to "Containerizing microservices" guide instead of "Using Docker containers for iterative development" guide.

This is for link in the "Containerizing the application" section.

@justineechen @gkwan-ibm

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/draft-guide-sessions/commit/5a89f767c6ea5a0ea1e0e204c41783d230050242

**Comment by gkwan-ibm** [comment]
if we decide the new docker guide/repo name as guide-containerize, the url will need to be updated as `https://openliberty.io/guides/containerize.html`
