### ISSUE TITLE
Add a description of using clone Id

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-sessions#59]
Based on https://github.com/OpenLiberty/guides-common/issues/106#issuecomment-537159021, the guide may need to talk about clone Id.

info: https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_admin_session_persistence_jcache.html

**Comment by evelinec** [comment]
- pending on Gilbert to review addressed feedback

**Comment by DannyS03** [comment]
No need to mention clone id after SME consultation.
