### ISSUE TITLE
Is it possible to run the guide-sessions with 2 instances on the same pc ?

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/guide-sessions#89]
Hi !

I wanted to test the guide-sessions app without docker on my pc. I have startet two server instances with different ports.
At first glance everything looks good in the log.
On server 1 with port 9080
````
CWWKT0016I: Webanwendung verfügbar: (default_host): http://desktop-p84migh:9080/guide-sessions/
[INFORMATION] [192.168.1.111]:5701 [CartCluster] [3.12.6] 
[INFO] 
[INFO] Members {size:2, ver:2} [
[INFO] 	Member [192.168.1.111]:5701 - 53ea0850-a7bb-488f-9de7-d0f97af48449 this
[INFO] 	Member [192.168.1.111]:5702 - 920d8d93-226f-4c04-b228-3410ff3f287a
[INFO] ]
````
and on second server port 9081 ..
````
[AUDIT   ] CWWKT0016I: Webanwendung verfügbar: (default_host): http://desktop-p84migh:9081/guide-sessions/
[INFORMATION] [192.168.1.111]:5702 [CartCluster] [3.12.6] 
[INFO] 
[INFO] Members {size:2, ver:2} [
[INFO] 	Member [192.168.1.111]:5701 - 53ea0850-a7bb-488f-9de7-d0f97af48449
[INFO] 	Member [192.168.1.111]:5702 - 920d8d93-226f-4c04-b228-3410ff3f287a this
[INFO] ]
```` 
So i tried to open http://localhost:9080/openapi/ui/ and added a item to the cart ..

The result of GET http://localhost:9080/guide-sessions/cart was
````
{"pod-name":"localhost","session-id":"STkYkcHcgv0nE-lfjASPdy5","cart":["test2 | $345.0"],"subtotal":345.0}
````

I thougt it should be possible now to open GET http://localhost:9081/guide-sessions/cart in the same chrome-tab.
(The JSESSIONID was succesfully send via REQUEST_HEADER)  
But i got a new JSESSIONID from server and of course the result of GET http://localhost:9081/guide-sessions/car was empty
````
{"pod-name":"localhost","session-id":"xZSNGUPp16BbTTUuepyb2lo","cart":[],"subtotal":0.0}
````

I read a little bit about hazelcast but i think it should work also with two instanes on the same pc with the group tag in the hazelcast-config.xml file.

Can you tell me what i make wrong here ?

Thanks much !

**Comment by c-koell** [comment]
@gkwan-ibm do you think its a bug in openliberty or do i have misconfigured hazelcast ?

**Comment by gkwan-ibm** [comment]
hi @c-koell, Thank you to ask this question. We are investigating your scenario.

**Comment by gkwan-ibm** [comment]
hi @c-koell,

In your case, we guess that your servers are located in different directories. Although both server.xml files are the same but the hazelcast config are in different places. It causes Hazelcast in construction of different cache managers.  Each server creates it's own cache for sessions. You may try the following by updating both server.xml as
```
    <httpSessionCache libraryRef="jCacheVendorLib" >
        <properties hazelcast.config.location="file:${server.config.dir}/hazelcast-config.xml"/>
    </httpSessionCache>
```
or make both `uri` point to a same location
```
uri="file:/same.location/hazelcast-config.xml"
```

**Comment by c-koell** [comment]
Hi @gkwan-ibm !

Thanks for investigating. It's really strange for me that it must be the same file and not only the same content but as you mentioned it works if i use the same file :-)

Is this a special behaviour if it runs on the same pc ? I think if i deploy the application on different servers it must not be the same file or ?

thanks 
claus

**Comment by gkwan-ibm** [comment]
@c-koell 

It should work for different servers if the uri for them are same.

**Comment by c-koell** [comment]
ok thanks for the info
